program: specified_gpu_wandb.py
description: Sweep for Cell-Segmentation
method: random
metric:
  goal: maximize
  name: average_fsim
parameters:
  learning_rate:
    min: 0.0001
    max: 0.004
  epochs:
    value: 1000
  batch_size:
    values: [2]
  n_filter:
    values: [16]
  model:
    values: ["cbam"]
  input_shape:
    values: [512, 256]
  kernel_size:
    values: [3, 5]