program: specified_gpu_wandb.py
description: Sweep for Cell-Segmentation
method: bayes
metric:
  goal: maximize
  name: val_dice_scoring
parameters:
  learning_rate:
    min: 0.0001
    max: 0.001
  epochs:
    value: 1000
  batch_size:
    values: [4, 8]
  n_filter:
    values: [16, 32]
  model:
    values: ["unet", "unet++"]
  input_shape:
    values: [512, 256]
  kernel_size:
    values: [3, 5]