program: specified_gpu_wandb.py
description: Sweep for Cell-Segmentation
method: random
metric:
  goal: maximize
  name: average_fsim
parameters:
  learning_rate:
    min: 0.0001
    max: 0.004
  epochs:
    values: [100, 1000]
  batch_size:
    values: [1]
  n_filter:
    values: [16]
  model:
    values: ["unet_multi"]
  input_shape:
    values: [512]
  kernel_size:
    values: [3, 5]
  multi:
    values: [True]