program: wandb_train.py
description: Sweep for Cell-Segmentation
method: random
metric:
  goal: maximize
  name: val_dice_scoring
parameters:
  learning_rate:
    min: 0.0001
    max: 0.001
  epochs:
    value: 800
  batch_size:
    values: [8, 16, 32]
  model:
    values: ["unet", "unet++"]
  input_shape:
    values: [512, 256]
  augment:
    values: [True, False]