description: Sweep for Cell-Segmentation
method: random
metric:
  goal: maximize
  name: average_fsim
parameters:
  batch_size:
    values: [1]
  epochs:
    values: [100]
  input_shape:
    values: [512]
  kernel_size:
    values: [3, 5, 7]
  learning_rate:
    distribution: uniform
    max: 0.004
    min: 0.0001
  model:
    values: [unet_multi]
  multiple_sizes:
    values: [true]
  n_filter:
    values: [16, 32]
  depth:
    values: [4, 5, 6, 8]
  dilation_rate:
    values: [1, 2]
  activation:
    values: ["selu", "relu", "leaky_relu"]
  use_batchnorm:
    values: [true, false]
  dropout_rate:
    values: [0.0, 0.2, 0.5]
program: specified_gpu_wandb_full_res_inference.py
